apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-server
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: java-server
  template:
    metadata:
      labels:
        app: java-server
    spec:
      containers:
      - image: rahulpatil1992/myhub:d75e9274
        name: java-server
        ports:
        - containerPort: 8081
